import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const importPure=async path=>import('data:text/javascript;base64,'+Buffer.from(readFileSync(new URL('../'+path,import.meta.url),'utf8')).toString('base64'));
const {backDestination}=await importPure('Navigation.js');
const {STAR_REWARDS,availableStars,purchaseReward,equipReward}=await importPure('StarShop.js');
const {normalizeProgress,makeBackup,parseBackup,PROGRESS_KEY}=await importPure('ProgressStorage.js');
assert.equal(backDestination('home'),null);
assert.equal(backDestination('shop'),'home');
assert.equal(backDestination('bank'),'home');
assert.equal(backDestination('quiz','bank'),'bank');
assert.equal(backDestination('curriculumLesson'),'curriculum');
assert.equal(backDestination('quiz','test'),'testChoose');
assert.equal(backDestination('quiz','game'),'gameChoose');
assert.equal(backDestination('quiz','review'),'reviewPlan');
assert.equal(backDestination('shark'),'sharkChoose');
assert.equal(backDestination('dragGame'),'home');
const old=normalizeProgress({history:[{total:4}],seen:['old'],stars:9,badges:['Brave'],stages:{numbers:2},lessonsDone:['MK4-001']});
assert.equal(PROGRESS_KEY,'mathkid4_v1_progress');
assert.equal(availableStars(old),9);
assert.equal(old.starSpent,0);
assert.deepEqual(old.ownedRewards,[]);
const bought=purchaseReward(old,'explorer');
assert.equal(bought.ok,true);
assert.equal(availableStars(bought.progress),6);
assert.equal(bought.progress.stars,9);
assert.deepEqual(bought.progress.stages,{numbers:2});
assert.deepEqual(bought.progress.badges,['Brave']);
assert.deepEqual(bought.progress.lessonsDone,['MK4-001']);
assert.equal(purchaseReward(bought.progress,'explorer').reason,'owned');
assert.equal(purchaseReward(bought.progress,'castle').reason,'insufficient');
assert.equal(equipReward(old,'dragon').ok,false);
const second=purchaseReward(bought.progress,'astronaut');
assert.equal(second.ok,true);
const equipped=equipReward(second.progress,'explorer');
assert.equal(equipped.ok,true);
assert.equal(equipped.progress.equippedReward,'explorer');
assert.equal(availableStars(equipped.progress),1);
const restored=parseBackup(JSON.stringify(makeBackup(equipped.progress,'general')));
assert.equal(restored.stars,9);
assert.equal(restored.starSpent,8);
assert.deepEqual(restored.ownedRewards,['explorer','astronaut']);
assert.equal(restored.equippedReward,'explorer');
assert.equal(STAR_REWARDS.length,6);
console.log('PASS: navigation, reward balance, purchase safety, progress migration and backup roundtrip');
