import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const src=readFileSync(new URL('../ProgressStorage.js',import.meta.url),'utf8');
const {PROGRESS_KEY,PRE_RESTORE_KEY,normalizeProgress,makeBackup,parseBackup,progressSummary}=await import('data:text/javascript;base64,'+Buffer.from(src).toString('base64'));
assert.equal(PROGRESS_KEY,'mathkid4_v1_progress');
assert.notEqual(PRE_RESTORE_KEY,PROGRESS_KEY);
const old={history:[{total:3,correct:2}],seen:['one'],stars:6,badges:['Explorer'],stages:{numbers:2},lessonsDone:['MK4-001'],currentLesson:'MK4-002',book:'general',lessonChecks:{'MK4-001':{correct:true}},custom:'keep-me'};
const back=makeBackup(old,'general');
assert.equal(back.version,2);
const restored=parseBackup(JSON.stringify(back));
assert.deepEqual(restored,normalizeProgress(old));
assert.equal(restored.custom,'keep-me');
assert.deepEqual(progressSummary(restored),{sessions:1,answered:3,stars:6,lessons:1});
const oldV1={...back,version:1};
assert.equal(parseBackup(JSON.stringify(oldV1)).stars,6);
assert.throws(()=>parseBackup(JSON.stringify({...back,format:'unknown'})));
assert.throws(()=>parseBackup(JSON.stringify({...back,progress:{}})));
assert.throws(()=>parseBackup('not json'));
assert.deepEqual(normalizeProgress({}).history,[]);
console.log('PASS: legacy key, V1/V2 backups, unknown fields and recovery validation');
